name: Pedal with Pete E2E Setup

description: |
  Guard against regressions due to dependency updates 
  on Pedal with Pete websites

# inputs:
#   website_url:
#     description: URL for the web property to test
#     default: https://pedalwithpete.org
#     required: true
outputs:
  pnpm_store_path:
    description: PNPM store path
    value: ${{ steps.pnpm-cache.outputs.STORE_PATH }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    # Install NPM dependencies
    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    # PNPM setup github action: https://github.com/pnpm/action-setup
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Check PNPM store path
      shell: bash
      run: |
        echo "STORE_PATH=${{ steps.pnpm-cache.outputs.STORE_PATH }}"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # # and run all Cypress tests
    # - name: E2E on Chrome
    #   # Cypress github action: https://github.com/cypress-io/github-action
    #   uses: cypress-io/github-action@v4
    #   with:
    #     browser: chrome
    #     start: pnpm test
    #   env:
    #     WEBSITE_URL: ${{ inputs.website_url }}
